language: java
script: gradle clean jar
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradle/wrapper/gradle-wrapper.jar
branches:
  only:
    - master
    - 3.2
notifications:
  email: false
before_install:
  - export TZ=Asia/Shanghai