sudo: false
language: java
script: gradle clean jar
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
branches:
  only:
    - master
    - 3.2
notifications:
  email: false
before_install:
  - export TZ=Asia/Shanghai