language: java
script: gradle clean jar
jdk:
  - oraclejdk8
  
sudo: required

before_install:
  - chmod +x gradlew
  - export TZ=Asia/Shanghai
branches:
  only:
    - master
    - 3.2
notifications:
  email: false
