language: java
sudo: required
branches:
  only:
    - master
    - 3.3
jdk:
  - openjdk8
before_install:
  - chmod +x gradlew
  - export TZ=Asia/Shanghai
script:
  - ./gradlew clean
  - ./gradlew build
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false